# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 18:34
from __future__ import unicode_literals

from django.db import migrations, models
import users.utils


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_birthday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='random_int',
            field=models.PositiveSmallIntegerField(default=users.utils.get_random_value, verbose_name='Random integer'),
        ),
    ]
