# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-14 19:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_random_int'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday_date',
            field=models.DateField(null=True, verbose_name='User birthday date'),
        ),
    ]
